/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CommunityHealthRouteImport } from './routes/community-health'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ForYouRouteImport } from './routes/for-you'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MapRouteImport } from './routes/map'
import { Route as NeighborhoodRouteImport } from './routes/neighborhood'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SponsorshipRouteImport } from './routes/sponsorship'
import { Route as StoryRouteImport } from './routes/story'
import { Route as WorkAfter55RouteImport } from './routes/work-after-55'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ResourceIdRouteImport } from './routes/resource.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityHealthRoute = CommunityHealthRouteImport.update({
  id: '/community-health',
  path: '/community-health',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForYouRoute = ForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodRoute = NeighborhoodRouteImport.update({
  id: '/neighborhood',
  path: '/neighborhood',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipRoute = SponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAfter55Route = WorkAfter55RouteImport.update({
  id: '/work-after-55',
  path: '/work-after-55',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceIdRoute = ResourceIdRouteImport.update({
  id: '/resource/$id',
  path: '/resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/changelog': typeof ChangelogRoute
  '/community-health': typeof CommunityHealthRoute
  '/demo': typeof DemoRoute
  '/for-you': typeof ForYouRoute
  '/help': typeof HelpRoute
  '/learn': typeof LearnRoute
  '/live': typeof LiveRoute
  '/map': typeof MapRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/sponsorship': typeof SponsorshipRoute
  '/story': typeof StoryRoute
  '/work-after-55': typeof WorkAfter55Route
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/resource/$id': typeof ResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/changelog': typeof ChangelogRoute
  '/community-health': typeof CommunityHealthRoute
  '/demo': typeof DemoRoute
  '/for-you': typeof ForYouRoute
  '/help': typeof HelpRoute
  '/learn': typeof LearnRoute
  '/live': typeof LiveRoute
  '/map': typeof MapRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/sponsorship': typeof SponsorshipRoute
  '/story': typeof StoryRoute
  '/work-after-55': typeof WorkAfter55Route
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/resource/$id': typeof ResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/changelog': typeof ChangelogRoute
  '/community-health': typeof CommunityHealthRoute
  '/demo': typeof DemoRoute
  '/for-you': typeof ForYouRoute
  '/help': typeof HelpRoute
  '/learn': typeof LearnRoute
  '/live': typeof LiveRoute
  '/map': typeof MapRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/sponsorship': typeof SponsorshipRoute
  '/story': typeof StoryRoute
  '/work-after-55': typeof WorkAfter55Route
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/resource/$id': typeof ResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/changelog'
    | '/community-health'
    | '/demo'
    | '/for-you'
    | '/help'
    | '/learn'
    | '/live'
    | '/map'
    | '/neighborhood'
    | '/onboarding'
    | '/opportunities'
    | '/partners'
    | '/privacy'
    | '/sponsorship'
    | '/story'
    | '/work-after-55'
    | '/admin/analytics'
    | '/resource/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/changelog'
    | '/community-health'
    | '/demo'
    | '/for-you'
    | '/help'
    | '/learn'
    | '/live'
    | '/map'
    | '/neighborhood'
    | '/onboarding'
    | '/opportunities'
    | '/partners'
    | '/privacy'
    | '/sponsorship'
    | '/story'
    | '/work-after-55'
    | '/admin/analytics'
    | '/resource/$id'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/changelog'
    | '/community-health'
    | '/demo'
    | '/for-you'
    | '/help'
    | '/learn'
    | '/live'
    | '/map'
    | '/neighborhood'
    | '/onboarding'
    | '/opportunities'
    | '/partners'
    | '/privacy'
    | '/sponsorship'
    | '/story'
    | '/work-after-55'
    | '/admin/analytics'
    | '/resource/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ChangelogRoute: typeof ChangelogRoute
  CommunityHealthRoute: typeof CommunityHealthRoute
  DemoRoute: typeof DemoRoute
  ForYouRoute: typeof ForYouRoute
  HelpRoute: typeof HelpRoute
  LearnRoute: typeof LearnRoute
  LiveRoute: typeof LiveRoute
  MapRoute: typeof MapRoute
  NeighborhoodRoute: typeof NeighborhoodRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  SponsorshipRoute: typeof SponsorshipRoute
  StoryRoute: typeof StoryRoute
  WorkAfter55Route: typeof WorkAfter55Route
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  ResourceIdRoute: typeof ResourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-health': {
      id: '/community-health'
      path: '/community-health'
      fullPath: '/community-health'
      preLoaderRoute: typeof CommunityHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-you': {
      id: '/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof ForYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhood': {
      id: '/neighborhood'
      path: '/neighborhood'
      fullPath: '/neighborhood'
      preLoaderRoute: typeof NeighborhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorship': {
      id: '/sponsorship'
      path: '/sponsorship'
      fullPath: '/sponsorship'
      preLoaderRoute: typeof SponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-after-55': {
      id: '/work-after-55'
      path: '/work-after-55'
      fullPath: '/work-after-55'
      preLoaderRoute: typeof WorkAfter55RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/$id': {
      id: '/resource/$id'
      path: '/resource/$id'
      fullPath: '/resource/$id'
      preLoaderRoute: typeof ResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ChangelogRoute: ChangelogRoute,
  CommunityHealthRoute: CommunityHealthRoute,
  DemoRoute: DemoRoute,
  ForYouRoute: ForYouRoute,
  HelpRoute: HelpRoute,
  LearnRoute: LearnRoute,
  LiveRoute: LiveRoute,
  MapRoute: MapRoute,
  NeighborhoodRoute: NeighborhoodRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  SponsorshipRoute: SponsorshipRoute,
  StoryRoute: StoryRoute,
  WorkAfter55Route: WorkAfter55Route,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  ResourceIdRoute: ResourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
