/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ForYouRouteImport } from './routes/for-you'
import { Route as HelpRouteImport } from './routes/help'
import { Route as NeighborhoodRouteImport } from './routes/neighborhood'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ResourceIdRouteImport } from './routes/resource.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForYouRoute = ForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodRoute = NeighborhoodRouteImport.update({
  id: '/neighborhood',
  path: '/neighborhood',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceIdRoute = ResourceIdRouteImport.update({
  id: '/resource/$id',
  path: '/resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/changelog': typeof ChangelogRoute
  '/demo': typeof DemoRoute
  '/for-you': typeof ForYouRoute
  '/help': typeof HelpRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/story': typeof StoryRoute
  '/resource/$id': typeof ResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/changelog': typeof ChangelogRoute
  '/demo': typeof DemoRoute
  '/for-you': typeof ForYouRoute
  '/help': typeof HelpRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/story': typeof StoryRoute
  '/resource/$id': typeof ResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/changelog': typeof ChangelogRoute
  '/demo': typeof DemoRoute
  '/for-you': typeof ForYouRoute
  '/help': typeof HelpRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/story': typeof StoryRoute
  '/resource/$id': typeof ResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/changelog'
    | '/demo'
    | '/for-you'
    | '/help'
    | '/neighborhood'
    | '/onboarding'
    | '/partners'
    | '/privacy'
    | '/story'
    | '/resource/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/changelog'
    | '/demo'
    | '/for-you'
    | '/help'
    | '/neighborhood'
    | '/onboarding'
    | '/partners'
    | '/privacy'
    | '/story'
    | '/resource/$id'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/changelog'
    | '/demo'
    | '/for-you'
    | '/help'
    | '/neighborhood'
    | '/onboarding'
    | '/partners'
    | '/privacy'
    | '/story'
    | '/resource/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ChangelogRoute: typeof ChangelogRoute
  DemoRoute: typeof DemoRoute
  ForYouRoute: typeof ForYouRoute
  HelpRoute: typeof HelpRoute
  NeighborhoodRoute: typeof NeighborhoodRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  StoryRoute: typeof StoryRoute
  ResourceIdRoute: typeof ResourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-you': {
      id: '/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof ForYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhood': {
      id: '/neighborhood'
      path: '/neighborhood'
      fullPath: '/neighborhood'
      preLoaderRoute: typeof NeighborhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/$id': {
      id: '/resource/$id'
      path: '/resource/$id'
      fullPath: '/resource/$id'
      preLoaderRoute: typeof ResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ChangelogRoute: ChangelogRoute,
  DemoRoute: DemoRoute,
  ForYouRoute: ForYouRoute,
  HelpRoute: HelpRoute,
  NeighborhoodRoute: NeighborhoodRoute,
  OnboardingRoute: OnboardingRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  StoryRoute: StoryRoute,
  ResourceIdRoute: ResourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
